spring.application.name=cloudflare-f2

# -- PostgreSQL -----------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/meditation
spring.datasource.username=backend
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# -- JPA / Hibernate ------------------------------------------
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# -- Liquibase -------------------------------------------------
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# -- Cloudflare R2 ---------------------------------------------
cloudflare.r2.account-id: d369c8b05ea2ed420f5407ea2f84fc3b
cloudflare.r2.access-key-id: 592532fd88d10793e459de7a539a29fc
cloudflare.r2.secret-access-key: f0638c8ce3e7cb4002a3f415fdd1d304c017e6c6223dc130c7306fc656c9456a

app.audio.presigned-url-duration-minutes: 1

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

server.port=8080

# -- Multipart uploads ----------------------------------------
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

#debug=true
